Add Undo/Redo Functions to editor
AmrDeveloper/CodeView pull request #8
Opened 2022-01-19 03:17 UTC by rudrathedev

2022-01-19 08:34 UTC, AmrDeveloper commented
Hello, @rudrathedev,

Thanks for your effort,

This code is good for Undo and Redo as we talk about the issue we need more general commands support and we need to design it to be customizable and easy,

So can you move your class UndoRedoManager to the app as an external helper class until we design our new commands support

After finishing it please squash your commits into a single one with commit, you can do it from CLI or Android Studio IDE

Thanks Again,
Amr Hesham

2022-01-19 08:37 UTC, AmrDeveloper requested changes

2022-01-19 08:37 UTC, AmrDeveloper commented on codeview/src/main/java/com/amrdeveloper/codeview/CodeView.java
> +    mUndoRedoManager.undo();
Undo and redo both call `mUndoRedoManager.undo();`

2022-01-19 08:37 UTC, AmrDeveloper commented on codeview/src/main/java/com/amrdeveloper/codeview/UndoRedoManager.java
> +            throws IllegalStateException {
Why we need `throws IllegalStateException`? btw `doRestorePersistentState` didn't throw any exception

2022-01-19 08:37 UTC, AmrDeveloper commented on codeview/src/main/java/com/amrdeveloper/codeview/UndoRedoManager.java
> +        return true;
This should can simplify to 

```java
return mEditHistory.mmPosition != -1;
```

2022-01-19 08:37 UTC, AmrDeveloper commented on codeview/src/main/java/com/amrdeveloper/codeview/UndoRedoManager.java
> +        private int mmPosition = 0;
Please change mm to single m

2022-01-19 08:37 UTC, AmrDeveloper commented on codeview/src/main/java/com/amrdeveloper/codeview/CodeView.java
> +    return mUndoRedoManager.canUndo();
Please make sure that your code is formatted

2022-01-23 16:01 UTC, AmrDeveloper commented
Hello @rudrathedev any updates?

2022-05-31 07:29 UTC, m-anshuman2166 commented
@AmrDeveloper we should close this since it is already implemented by you

2022-05-31 17:20 UTC, AmrDeveloper commented
You are right@m-anshuman2166, thank you

2022-05-31 17:20 UTC, closed without merging